In [9]:
import pandas as pd
import numpy as np
from pycaret.regression import setup, compare_models, evaluate_model, plot_model, get_config
from pandas_profiling import ProfileReport

In [2]:
data = pd.read_csv('data.csv', sep=";", usecols=["Feature 1", "Feature 2", "Feature 9", "Y"])
data.head()

       Y  Feature 1  Feature 2  Feature 9
0  13500         23      46986       1165
1  13750         23      72937       1165
2  13950         24      41711       1165
3  14950         26      48000       1165
4  13750         30      38500       1170

In [10]:
ProfileReport(data, title="Features 1_2_9 Profile").to_file("1_2_9_profile.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [5]:
s = setup(data, target = 'Y', feature_selection=True, categorical_features=["Feature 9"])

In [6]:
best = compare_models()

In [7]:
prep_pipe = get_config('prep_pipe') 
prep_pipe.transform(data)

,Feature 9_1114.0,Feature 9_1075.0,Feature 9_1160.0,Feature 9_1195.0,Feature 9_1140.0,Feature 9_1079.0,Feature 9_1085.0,Feature 9_1125.0,Feature 9_1105.0,Feature 9_1100.0,...,Feature 9_1110.0,Feature 9_1245.0,Feature 9_1180.0,Feature 9_1020.0,Feature 9_1095.0,Feature 9_1275.0,Feature 9_1615.0,Feature 9_1055.0,Feature 9_1065.0,Feature 9_1270.0
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1431,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1432,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1433,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1434,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1435,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
prep_pipe.transform(data).columns

Index(['Feature 9_1114.0', 'Feature 9_1075.0', 'Feature 9_1160.0',
       'Feature 9_1195.0', 'Feature 9_1140.0', 'Feature 9_1079.0',
       'Feature 9_1085.0', 'Feature 9_1125.0', 'Feature 9_1105.0',
       'Feature 9_1100.0', 'Feature 2', 'Feature 9_1010.0', 'Feature 9_1155.0',
       'Feature 9_1070.0', 'Feature 9_1025.0', 'Feature 9_1172.0',
       'Feature 9_1205.0', 'Feature 9_1320.0', 'Feature 9_1260.0',
       'Feature 9_1120.0', 'Feature 9_1150.0', 'Feature 9_1000.0',
       'Feature 9_1255.0', 'Feature 9_1050.0', 'Feature 9_1135.0',
       'Feature 9_1119.0', 'Feature 9_1121.0', 'Feature 9_1035.0',
       'Feature 9_1130.0', 'Feature 9_1090.0', 'Feature 9_1030.0', 'Feature 1',
       'Feature 9_1170.0', 'Feature 9_1265.0', 'Feature 9_1480.0',
       'Feature 9_1115.0', 'Feature 9_1015.0', 'Feature 9_1080.0',
       'Feature 9_1084.0', 'Feature 9_1040.0', 'Feature 9_1060.0',
       'Feature 9_1045.0', 'Feature 9_1165.0', 'Feature 9_1185.0',
       'Feature 9_1110.0', 'Feature 9_1245.0', 'Feature 9_1180.0',
       'Feature 9_1020.0', 'Feature 9_1095.0', 'Feature 9_1275.0',
       'Feature 9_1615.0', 'Feature 9_1055.0', 'Feature 9_1065.0',
       'Feature 9_1270.0'],
      dtype='object')